import Foundation
import ProjectDescription

let name = "FulliOS"

let workspace = Workspace(
    name: name,
    projects: [],
    schemes: [
        .scheme(name: name)
    ],
    generationOptions: Workspace.GenerationOptions.options(
        autogeneratedWorkspaceSchemes: .disabled))
