languages:
  - en

exclude:
  - Derived
  - Pods
  - Generated
  - Constants.swift

rules:
  - support_flat_case
  - support_one_line_comment
  - support_multi_line_comment
  - support_british_words
  - ignore_capitalization
  - ignore_swift_keywords
  - ignore_commonly_used_words
  - ignore_shortened_words
  - ignore_lorem_ipsum
  - ignore_html_tags
  - ignore_urls

ignore:
  - fulli
