# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - ./FulliOS
  - ./FulliOSTests
  - ./FulliOSUITests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ./FulliOS/Sources/Generated/**
  - ./FulliOS/Sources/Apps/Camera/CameraView.swift
  - ./Pods

disabled_rules:
  - explicit_type_interface
  - explicit_enum_raw_value

opt_in_rules:
  - array_init
  - nimble_operator
  - no_grouping_extension
  - attributes
  - private_over_fileprivate
  - strict_fileprivate
  - explicit_top_level_acl
  - trailing_whitespace
  - file_header
  - trailing_closure
  - switch_case_alignment
  - let_var_whitespace
  - opening_brace
  - void_return
  - first_where
  - number_separator
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_outlet
  - protocol_property_accessors_order
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - statement_position
  - superfluous_disable_command
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate
  - xctfail_message

custom_rules:
  no_fatal_errors:
    included: ".*.swift"
    name: "Crash"
    regex: "fatalError"
    message: "Don't use fatalError()"
    severity: warning

  swiftlint_file_disabling:
    included: ".*.swift"
    name: "SwiftLint File Disabling"
    regex: "swiftlint:disable\\s"
    match_kinds:
      - comment
    message: "Prefer swiftlint:disable:next or swiftlint:disable:this"
    severity: warning

  optional_try:
    included: ".*.swift"
    name: "Optional Try"
    regex: "(try[!,?])"
    message: "You should wrap a `try` in a `do/catch` loop rather than forcibly or optionally attempting it."
    severity: warning

  public_ui_model:
    included: ".*.swift"
    name: "Public UIModel"
    regex: "^(open |private |internal |)(class|struct) [a-zA-Z]+(?i)UI(Model|DAO)"
    message: "UIModel must be public only."
    severity: error

  non_public_datamodel:
    included: ".*.swift"
    name: "Non Public Data Model"
    regex: "^(open |private |public )(class|struct) [a-zA-Z]+(?i)(Request|Response)(Model|DAO|)"
    message: "Data Model must be internal only."
    severity: error

  non_public_datasource:
    included: ".*.swift"
    name: "Non Public DataSource"
    regex: "^(open |private |public )(class|struct) [a-zA-Z]+(?i)DataSource"
    message: "Data Source must be internal only."
    severity: error

  dont_import_uikit:
    included: ".*(?i)(ViewModel|Model|DataSource).swift"
    name: "Don't import UIKit in ViewModel"
    regex: "^import (UIKit)$"
    message: "Don't import UIKit in ViewModel/ Model / DataSource"
    severity: error

  avoid_print:
    included: ".*.swift"
    name: "Avoid Print"
    regex: "print\\("
    message: "Consider using a logging method instead of print"
    severity: warning

  hardcoded_font:
    included: ".*.swift"
    name: "Hardcoded Font Usage"
    regex: '\.font\(\.custom\("[^"]+", size: \d+\)\)'
    message: "Avoid using hardcoded font strings. Consider using a font manager or constants."
    severity: warning

  non_localized_string:
    included: ".*\\.swift"
    name: "Non-localized String Usage"
    regex: '\bText\("[^"]+"\)|\bButton\("[^"]+",'
    message: "Use localized strings for Text and Button labels to support internationalization."
    severity: warning

# Rules configuration

closure_spacing:
  severity: error

colon:
  severity: error

force_unwrapping:
  severity: warning

force_cast:
  severity: warning

force_try:
  severity: warning

control_statement:
  severity: warning

cyclomatic_complexity:
  warning: 25
  error: 30

explicit_init:
  severity: error

file_length:
  warning: 25000
  error: 30000

first_where:
  severity: error

function_body_length:
  warning: 70
  error: 100

function_parameter_count:
  warning: 8
  error: 10

generic_type_name:
  min_length:
    warning: 0
    error: 1
  max_length:
    warning: 80
    error: 100

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length:
    warning: 40
    error: 50
  validates_start_with_lowercase:
    severity: warning

implicitly_unwrapped_optional:
  severity: error

large_tuple:
  warning: 4
  error: 6

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_nsgeometry_functions:
  severity: error

line_length:
  warning: 25000
  error: 30000
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

mark:
  severity: warning

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

notification_center_detachment:
  severity: error

number_separator:
  severity: error

object_literal:
  severity: error

operator_whitespace:
  severity: error

operator_usage_whitespace:
  severity: error

overridden_super_call:
  severity: error

private_outlet:
  severity: error

private_unit_test:
  severity: error

prohibited_super_call:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: error

statement_position:
  statement_mode: default
  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

trailing_comma:
  severity: warning

trailing_newline: error

trailing_semicolon:
  severity: error

type_body_length:
  warning: 8000
  error: 10000

type_name:
  min_length:
    warning: 0
    error: 3
  max_length:
    warning: 80
    error: 100

unused_closure_parameter:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding:
  severity: error

valid_ibinspectable:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_whitespace:
  severity: error

weak_delegate:
  severity: error

reporter: "xcode"
